blank_issues_enabled: false
contact_links:
  - name: Author
    url: https://www.thescottclan.org/jason/
    about: Please ask and answer questions here.
  - name: Family
    url: https://www.thescottclan.org/
    about: Please report security vulnerabilities here.
